name: Build for desktop

on: [push]
#on:
#  push:
#    branches:
#      - master

env:
  KIVY_GL_BACKEND: angle_sdl2

jobs:

  pyinstaller-windows-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'blog2epub_windows.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: blog2epub_win32_v1.5.0
      - name: Create installer
        run: |
          choco install nsis          
          & 'C:\Program Files (x86)\NSIS\makensis' .\blog2epub_windows_installer.nsi
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: blog2epub_1.5.0_setup.exe
          path: ./dist/blog2epub_1.5.0_setup.exe
          compression-level: 0
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.SFTP_UPLOAD_HOST}}
          username: ${{secrets.SFTP_UPLOAD_USERNAME}}
          password: ${{secrets.SFTP_UPLOAD_PASSWORD}}
          port: 22
          uploads: |
            ./dist/blog2epub_1.5.0_setup.exe => /home/${{secrets.SFTP_UPLOAD_USERNAME}}/blog2epub_1.5.0_setup.exe

  pyinstaller-macos-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'blog2epub_macos.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'blog2epub.app'
      - name: Upload dng
        run: bash ./make_macos_dmg.sh
      - uses: actions/upload-artifact@v4
        with:
          name: blog2epub_v1.5.0_macos.dmg
          path: ./dist/blog2epub_v1.5.0_macos.dmg
          compression-level: 0
      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.SFTP_UPLOAD_HOST}}
          username: ${{secrets.SFTP_UPLOAD_USERNAME}}
          password: ${{secrets.SFTP_UPLOAD_PASSWORD}}
          port: 22
          uploads: |
            ./dist/blog2epub_v1.5.0_macos.dmg => /home/${{secrets.SFTP_UPLOAD_USERNAME}}/blog2epub_1.5.0_setup.dmg
