name: Build macOS

on: [push]
#on:
#  push:
#    branches:
#      - master

env:
  KIVY_GL_BACKEND: angle_sdl2

jobs:
  pyinstaller-windows-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'blog2epub_macos.spec'
          requirements: 'requirements.txt'
          # upload_exe_with_name: 'blog2epub_macos_v1.5.0'
      - name: Upload dng
        uses: actions/upload-artifact@v4
        with:
          name: blog2epub_macos_v1.5.0
          path: ./dist/blog2epub.app