name: Build for desktop

on: [push]
#on:
#  push:
#    branches:
#      - master

env:
  KIVY_GL_BACKEND: angle_sdl2

jobs:

#  windows-build:
#    runs-on: windows-latest
#    steps:
#      - name: Create Executable
#        uses: sayyid5416/pyinstaller@v1
#        with:
#          python_ver: '3.12'
#          spec: 'blog2epub_windows.spec'
#          requirements: 'requirements.txt'
#          upload_exe_with_name: blog2epub_v1.5.0_win32
#      - name: Create installer
#        run: |
#          choco install nsis
#          & 'C:\Program Files (x86)\NSIS\makensis' .\blog2epub_windows_installer.nsi
#      - name: Upload installer
#        uses: actions/upload-artifact@v4
#        with:
#          name: blog2epub_1.5.0_setup.exe
#          path: ./dist/blog2epub_1.5.0_setup.exe
#          compression-level: 0
#
#  macos-build:
#    runs-on: macos-latest
#    steps:
#      - name: Create Executable
#        uses: sayyid5416/pyinstaller@v1
#        with:
#          python_ver: '3.12'
#          spec: 'blog2epub_macos.spec'
#          requirements: 'requirements.txt'
#          upload_exe_with_name: 'blog2epub.app'
#      - name: Make and upload dng
#        run: bash ./make_macos_dmg.sh
#      - uses: actions/upload-artifact@v4
#        with:
#          name: blog2epub_v1.5.0_macos.dmg
#          path: ./dist/blog2epub_v1.5.0_macos.dmg

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libsdl2-dev libmtdev-dev libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 xclip xsel
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'blog2epub_linux.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: blog2epub_v1.5.0_linux
      - name: Create installer
        run: |
          wget -O appimagetool-x86_64.AppImage https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool-x86_64
          bash ./make_linux_appimage.sh
      - uses: actions/upload-artifact@v4
        with:
          name: blog2epub_v1.5.0.AppImage
          path: ./dist/blog2epub_v1.5.0.AppImage