name: Linux build

on: [push]

#on:
#  push:
#    branches:
#      - master

env:
  KIVY_GL_BACKEND: angle_sdl2

jobs:

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Whereiam
        run: |
          pwd
          ls -al
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libmtdev-dev libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0
          sudo apt-get install -y libsdl2-ttf-2.0-0 libsdl2-image-dev xclip xsel
      - name: Create Executable
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          spec: 'blog2epub_linux.spec'
      - uses: actions/upload-artifact@v4
        with:
          name: blog2epub_v1.5.0_linux
          path: /src/dist/blog2epub
          if-no-files-found: error
      - name: Create installer
        run: |
          wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
          bash ./make_linux_appimage.sh
      - uses: actions/upload-artifact@v4
        with:
          name: blog2epub_v1.5.0.AppImage
          path: /src/dist/blog2epub_v1.5.0.AppImage
          if-no-files-found: error
